### ISSUE TITLE
Where the money at?!

### ISSUE THREAD

**Issue by randallmeeker** [JavaScriptMN/JavaScriptMN#13]
Need to decide on a bank and open checking account once were filed with the state.

**Comment by randallmeeker** [comment]
I'm thinking something local, like a local credit union or something.

**Comment by brampersandon** [comment]
Here are some credit unions in town.

- [City and County](https://www.cccu.com/)
- [Spire](https://www.myspire.com/)
- [Wings](https://www.wingsfinancial.com/home)
- [Firefly](https://www.fireflycu.org/)
- [Affinity Plus](https://www.affinityplus.org/)
- [TruStone](https://trustonefinancial.org/)

(have to dash atm, will add more later on)

**Comment by randallmeeker** [comment]
ah, yes I remember TruStone was the one I think we talked about during meeting. I'll +1 TruStone.

**Comment by randallmeeker** [comment]
We have decided on Wing. Closing.
