### ISSUE TITLE
Need bookkeeping solution

### ISSUE THREAD

**Issue by randallmeeker** [JavaScriptMN/JavaScriptMN#16]
- [x] Should allow for invoice creation
- [x] Should integrate with Stripe for payments
- [x] Should track expenses
- [x] Should allow multiple team members
- [x] Should be inexpensive to use

**Comment by randallmeeker** [comment]
My original thought was to create invoices through JotForm (supports stripe) and just keep track of everything else on a Google Sheet. That meets all the criteria I suppose.

**Comment by mwillbanks** [comment]
Wave: https://stripe.com/works-with/wave  Wave is almost entirely free (unless you pay people via W2).

**Comment by randallmeeker** [comment]
@mwillbanks you win this round! Next time your at a meetup lets get you a tshirt or something. Wave is awesome.
