### ISSUE TITLE
April Speaker

### ISSUE THREAD

**Issue by randallmeeker** [JavaScriptMN/JavaScriptMN#17]

**Comment by wmsmacdonald** [comment]
Is anyone interested in hearing about service workers? I could probably do a lightning talk about them. I have a [project](https://github.com/wmsmacdonald/delta-cache-browser) that is a "creative" use of service workers, but I could also talk about using them for offline apps.

**Comment by randallmeeker** [comment]
@wmsmacdonald Sorry to get back to you so late. But that sounds great. If your up for an April spot we're looking at presentations around 30-45min. Interested? If you need a longer/shorter spot, let us know. We can make most anything work.

**Comment by wmsmacdonald** [comment]
@randallmeeker I don't think I have enough content for a full spot but I think 20 minutes might make sense.  Does that work?

**Comment by randallmeeker** [comment]
Sure thing. I'll put you down.

**Comment by zapplebee** [comment]
I've been working on a talk. Not sure if its enough for main but I'll have like 30 slides on "Capturing, analyzing, and manipulating video with JavaScript"

https://docs.google.com/presentation/d/1y5cj-HFZSiaWTGs7NEpBw6qEdglzTvMkYkT0m4Ul2ts/edit?usp=sharing

**Comment by randallmeeker** [comment]
@zapplebee that sound pretty sweet and like 30 slides, that I think meets the minimum for a keynote!

**Comment by zapplebee** [comment]
@randallmeeker Sounds great, thanks.
